a = int(input("Enter a number"))
b = int(input("Enter a number"))
c = int(input("Enter a number"))
d = int(input("Enter a number"))
e = int(input("Enter a number"))
f = int(input("Enter a number"))
g = int(input("Enter a number"))
h = int(input("Enter a number"))

s = set()
s.add(a)
s.add(b)
s.add(c)
s.add(d)
s.add(e)
s.add(f)
s.add(g)
s.add(h)

print(s)